### ISSUE TITLE
[Question] Should android calling apps use ConnectionService?

### ISSUE THREAD

**Issue by VictorUvarov** [voximplant/flutter_demos#11]
Is local notifications enough for a call app? Or do we also need [ConnectionService](https://developer.android.com/reference/android/telecom/ConnectionService.html)?

**Comment by VladimirBrejcha** [comment]
@VictorUvarov, thank you for the feedback. The application is not required to use the ConnectionService, it is optional and depends on the requirements and tasks of the applications. From a technical point of view, you can use any option for displaying an incoming call. We do not have an example with ConnectionService yet, we will consider the possibility of making such an example.
