### ISSUE TITLE
cannot receive calls.

### ISSUE THREAD

**Issue by Shashoug** [voximplant/flutter_demos#12]
Hello guys. 
I want to use VoxImplant SDK so i can achieve audio calls functionality. 
i used the demo code and i've tried it. 
when i tried to implement it on my project i couldn't receive incoming calls.
the only functionality that works is making a call. 
the SDK log:
`1 callService(774489783): _onIncomingCall
2 flutter: caller is ***** 
3 flutter: [FlutterCallKit:INFO > FCXCallObserver.callChanged:   DA1279A6-1BCA-42F3-9F26-000C33000A81]
4 flutter: [FlutterCallKit:INFO > FCXProvider.reportNewIncomingCall]
5 flutter: [FlutterCallKit:INFO > FCXProvider.executeTransaction]
6 flutter: [FlutterCallKit:INFO > FCXTransaction.getActions]
7 flutter: [FlutterCallKit:INFO > FCXProvider.FCXEndCallAction]
8 flutter: -------- call declined -----------
9 flutter: [FlutterCallKit:INFO > FCXEndCallAction.fulfill]
10 flutter: [FlutterCallKit:INFO > FCXCallObserver.callChanged: DA1279A6-1BCA-42F3-9F26-000C33000A81]
[log] CallService(774489783): onCallDisconnected
11 flutter: call ended because FCXCallEndedReason.remoteEnded `

it seems like all incoming calls are rejected before incomingCall event launches the widget. 
any help guys?

**Comment by VladimirBrejcha** [comment]
@Shashoug thank you for the feedback! Could you please provide steps to reproduce the error so I can find it

**Comment by Shashoug** [comment]
Thanks in advance Vladimir
Can you provide me with the proper me with scenario of receiving and making
calls in the dashboard?
I looked up online but i think the problem is on my scenario.

**Comment by VladimirBrejcha** [comment]
@Shashoug 
Did you try this one?
```require(Modules.PushService);
VoxEngine.addEventListener(AppEvents.CallAlerting, (e) => {
const newCall = VoxEngine.callUserDirect(
  e.call, 
  e.destination,
  e.callerid,
  e.displayName,
  null
);
VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);
});

**Comment by VladimirBrejcha** [comment]
Close due to inactivity
