### ISSUE TITLE
Did you confirm 'performAnswerCallAction' callback fired

### ISSUE THREAD

**Issue by yukitaka13-1110** [voximplant/flutter_demos#2]
Hi!
In this callback,

https://github.com/voximplant/flutter_demos/blob/c152d9c1d5e944d15915a1fe6f9396593887ee6a/audio_call/lib/services/callkit_service.dart#L174-L183

Did you confirm this fired ?
I use `flutter_call_kit` but I can't confirm yet.
I confirmed only `didActivateAudioSession` and `performEndCallAction` fired.

**Comment by VladimirBrejcha** [comment]
Hi, @yukitaka13-1110 ,
Just checked with audio_call demo, _performAnswerCallAction being correctly fired on answer incoming call

**Comment by yukitaka13-1110** [comment]
@VladimirBrejcha 
Sorry, I realize I use version 0.0.2.
I confirmed just now.
Thank you so much!
