### ISSUE TITLE
Video call - Closing the video stream on both ends then opening it on one Side doesn't send the stream to the other end.

### ISSUE THREAD

**Issue by EssamOmar1994** [voximplant/flutter_demos#4]
Hello !

I'm trying to use the video demo and I want to start the call with video not enabled for more Privacy. but I came across this issue.
Steps to reproduce: if I close the stream on both ends and one user opened the video stream the Other user doesn't get their image. 
So is that the way it's intended or can we have a workaround this.

**Comment by VladimirBrejcha** [comment]
Hi @EssamOmar1994 ,

That doesn't seem normal, you should definitely receive video stream in that case.
Is 'receive video' set to true in your app (on create/answer call)?
Also what is in your Vox Engine scenario?

**Comment by EssamOmar1994** [comment]
Hi @VladimirBrejcha 
yes I'm setting receive video to true on both functions and here is the scenario :
`require(Modules.PushService);
VoxEngine.addEventListener(AppEvents.CallAlerting, e => {
  const newCall = VoxEngine.callUser(e.destination, e.destination, e.displayName, {'VI-CallTimeout': '50'}, true);
  VoxEngine.easyProcess(e.call, newCall, ()=>{}, true);
});`

Thanks for your help

**Comment by VladimirBrejcha** [comment]
@EssamOmar1994 ,

We've looked into this issue and found out that there was a bug in Voximplant SDK. It is fixed in the 2.1.2 version and we've updated Demo to use latest version.
So the problem should be solved for now

Please try and let us know if you face any issues
