### ISSUE TITLE
Flutter Audio Call

### ISSUE THREAD

**Issue by FarhanAli001** [voximplant/flutter_demos#5]
I want to make an audio calling application in flutter but i didn't get any appropriate answer, i was able to make video calling with agora flutter but didn't find the audio calling source and i also tried voximplant but it didn't work, kindly give me the proper source code link, i will be very thankful

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 ,

We have 2 demo applications for flutter: audio call and video call. They are located in this repository.

Could you please provide more details about the issues you faced?

Best regards,
Yulia Grigorieva

**Comment by FarhanAli001** [comment]
The problem is that when i try to login from app, it shows error ' Invalid Username ' and so i am not able to use or test the app, i will be very thankful if you help me

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 ,

To use any Voximplant demo projects, you need first a Voximplant developer account. If you don't have one, please register on [our site](https://manage.voximplant.com/auth/sign_up).

Voximplant is a communications platform, so you need to make a setup of a Voximplant application in your account.
As it is described in the Readme file for the demo, you will need:
-    [Voximplant application](https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts/applications)
-    [two Voximplant users](https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts/users)
-   VoxEngine scenario (example is provided in the [Readme](https://github.com/voximplant/flutter_demos/tree/master/audio_call#voxengine-scenario-example) )
-   [routing setup](https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts/programmable_voice_and_video/routing)

After you create Voximplant users, you should be able to log in to the demo app with their credentials.

Please note that the demo app accepts user login in the format `user@application.account`, while the SDK API is called with full format `user@application.account.voximplant.com`. It is done to simplify login input on UI.

Please let me know if you have any questions.

Best regards,
Yulia Grigorieva

**Comment by FarhanAli001** [comment]
Thank you so much now i am logged in from application, but  unable to call from one user to another, kindly help me to make call, i will be very thankful to you

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 ,

Have you setup VoxEngine scenario and routing?

If yes, you should be able to call another user by entering its username.

Please provide more details about the issue.

Best regards,
Yulia Grigorieva

**Comment by FarhanAli001** [comment]
i have no idea how to setup scenario and routing, kindly help me, i will be very thankful to you

**Comment by YuliaGrigorieva** [comment]
You need to create a scenario in your Voximplant application in Voximplant Control Panel (https://manage.voximplant.com)

Select your application, open "Scenarios" tab and create a new file:
![изображение](https://user-images.githubusercontent.com/8545374/83167342-cbe08f00-a118-11ea-9ca4-fba859f3b768.png)
Then, add the scenario example from [readme file](https://github.com/voximplant/flutter_demos/tree/master/audio_call#voxengine-scenario-example)

To create a rule for routing, open "Routing" tab and create a rule
![изображение](https://user-images.githubusercontent.com/8545374/83167636-0ba77680-a119-11ea-819a-514207b78923.png)
In the "Available scenarios" dropdown, please select your scenario.

Then, try to make a call to another user by entering username in the input field in the demo app.

Best regards,
Yulia Grigorieva

**Comment by FarhanAli001** [comment]
Thank you so much, now i am able to call from one user to another, but Actually i want to make  conference call like 3 or 4 persons can talk in a single call, i just want to know, do this app work for conference call?

**Comment by FarhanAli001** [comment]
kindly reply

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 !

Voximplant platform and Voximplant Flutter SDK provides the API to make audio conference between multiple users. 
Please take a look at this tutorial: https://voximplant.com/docs/tutorials/voximplant-audio-conferencing
Please note that you will need a different VoxEngine scenario.

This demo application is designed for a base audio call between 2 users. As you can see, the UI is classic for audio call and is not adopted for multiple users within a call. 

However, there should be no issues to build an audio conference application using Voximplant Flutter SDK. After you setup a VoxEngine scenario, you can use the same SDK API as for audio call.
Please only consider to use [VIClient.conference](https://github.com/voximplant/flutter_voximplant/blob/bfaa5c3d44f7e0ce68fa73c79f4809153f59d0ff/lib/src/client/client.dart#L366) API to start a conference call.

Best regards,
Yulia Grigorieva

**Comment by FarhanAli001** [comment]
thank you for the reply but kindly explain step by step, i am getting confused with the process, just explain the whole process step by step to make a conference call, seting up scenanrios, rules, the code etc etc, i will be thankful to you

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 ,

Please take a look at this tutorial: https://voximplant.com/docs/tutorials/voximplant-audio-conferencing
It provides VoxEngine scenario example.

Best regards,
Yulia Grigorieva

**Comment by FarhanAli001** [comment]
I have studied this link's document briefly but didn't understand the process, i will be very thankful to you if you share the conference call project, i have already short of time to do this conference call task, kindly reply as soon as possible, i am saying again i will be very thankful to you

**Comment by YuliaGrigorieva** [comment]
Hello @FarhanAli001 !

Voximplant platform provides a lot of features and solutions.

Before implementing any solution, we recommend to take a look at the [Basic concepts](https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts) of the platform to understand how it works.

Unfortunately, we do not have the resources to implement the demo application for each type of solutions that can be done with the Voximplant platform.

If you have any specific questions, we can answer them and try to help to resolve the issues you face with.

Best regards,
Yulia Grigorieva
