### ISSUE TITLE
For using qusetion

### ISSUE THREAD

**Issue by LuLuSaBee** [voximplant/flutter_demos#6]
hi, I'm try to use audio call example
And find a problem, the login account and password
Should I use my own voximplant account ?
Or I need to link my account with this example

**Comment by YuliaGrigorieva** [comment]
Hello @lulusabee !

You need to set up a Voximplant application within your Voximplant account:
You'll need the following:
- Voximplant application (https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts/applications)
- two Voximplant users (https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts/users)
- VoxEngine scenario (you can use a scenario example from [Readme](https://github.com/voximplant/flutter_demos/tree/master/audio_call#voxengine-scenario-example)
- routing setup https://voximplant.com/docs/introduction/introduction_to_voximplant/basic_concepts/programmable_voice_and_video/routing)

Once the setup is completed, you should be able to log in with Voximplant user you have previously created. 
Voximplant user names are in the format: `user@application.account.voximplant.com`, the demo accepts the format `user@application.account`.

Please let me know if you faced any issues.

Best regards,
Yulia Grigorieva

**Comment by lulusabee** [comment]
Thank you for your helping
But there is a new problem, Error log:

[ERROR:flutterib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Default FirebaseApp is not initialized in this process com.voximplant.flutter.audio_call. Make sure to call FirebaseApp.initializeApp(Context) first., null)

Is this a problem with firebase?

**Comment by YuliaGrigorieva** [comment]
Hello @lulusabee ,

Please check that you have this line uncommented: 
https://github.com/voximplant/flutter_demos/blob/a1d433924fd0958cf9613fd9e3374c752566c487/audio_call/android/app/build.gradle#L70

This is an important step to enabling firebase in your project. Please also consider that this line will require valid "google-services.json" file in your project

We have commented out this line to allow the developers to build the project without firebase to check base functionality first.

Best regards,
Yulia Grigorieva

**Comment by vinhcuong** [comment]
Hi @YuliaGrigorieva 
I have some problem.
I run app and login, everything ok. But i can't call to another user, format fo call is user@application.account right ?
