### ISSUE TITLE
its showing just connecting but not started actual video call

### ISSUE THREAD

**Issue by sid9890** [voximplant/flutter_demos#7]
in video call demo flutter app, it gives me 
-NoSuchMethodError: The getter 'localVideoStream' was called on null.
and it shows calling screen when I click the accept button it opens the video calling screen but does not start a video call it shows only connecting.....what to do??? what I am missing????

**Comment by VladimirBrejcha** [comment]
Hello,
What device and OS version do you use?
In which state the app was at the moment of incoming call (foreground/background/dead/dead and locked)?

**Comment by sid9890** [comment]
that problem solved, but new issues raised
I need 3 scenarios where a video call or audio call should work,2 of them scenarios are working perfectly
1 scenario where it's not working is below:
when the receiver gets an incoming call and it gets connected and after the call ends the receiver goes to the background
and again the same receiver got another call then the receiver gets a notification, after a click on the notification it goes to IncomingCallPage
and shoes incoming calling screen for 1 second and automatically goes to MakeCallPage and shows 'Logged in as null' though its LoginPage state shows LoginLastUserLoaded or LoginSuccess and screen stuck there 

if I kill the app then it's working perfectly


Other 2 scenario working perfectly like:
when the app is killed
when the app is in the foreground

**Comment by VladimirBrejcha** [comment]
Moved to https://github.com/voximplant/flutter_demos/issues/8
