### ISSUE TITLE
Second call from the background bug

### ISSUE THREAD

**Issue by sid9890** [voximplant/flutter_demos#8]
that problem solved, but new issues raised
I need 3 scenarios where a video call or audio call should work,2 of them scenarios are working perfectly
1 scenario where it's not working is below:
when the receiver gets an incoming call and it gets connected and after the call ends the receiver goes to the background
and again the same receiver got another call then the receiver gets a notification, after a click on the notification it goes to IncomingCallPage
and shoes incoming calling screen for 1 second and automatically goes to MakeCallPage and shows 'Logged in as null' though its LoginPage state shows LoginLastUserLoaded or LoginSuccess and screen stuck there

if I kill the app then it's working perfectly

Other 2 scenario working perfectly like:
when the app is killed
when the app is in the foreground

**Comment by VladimirBrejcha** [comment]
Hi, 

i could'nt reproduce your case so I'll need the following info:
1. Device
2. OS
3. Logs

It seems like the app bug, so it will be fixed along with other bugs in the future updates
