### ISSUE TITLE
Can't use the Demo Project to login

### ISSUE THREAD

**Issue by XiauRay** [voximplant/flutter_demos#9]
I clone this demo project , but can't login .
I have been created applications & two users at the control panel to login, but still return the  "Invalid username" to me...
What else am I missing? please help me thanks

**Comment by VladimirBrejcha** [comment]
Hello XiauRay,
Login using Voximplant user name in the format _user@app.account_.
For example, for the user "Vladimir" in the application "Test" in the "VladimirBrejcha" account (all from control panel), I would enter `Vladimir@Test.VladimirBrejcha` to login in the demo app.
